export const AMENITIES_METADATA = [
  {
    name: 'Community Hall',
    description: 'A spacious venue for parties, workshops, and community gatherings.',
    icon: 'Users',
    thumbnail: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=400&q=80',
    price: 'Rs. 5000.00',
    location: 'Block A, Ground Floor',
    timings: { open: '09:00 AM', close: '11:00 PM' },
    rules: ['Advance booking required (48 hrs)', 'No loud music after 10 PM', 'Cleaning fee applies'],
  },
  {
    name: 'Tennis Court',
    description: 'Professional-grade clay courts for tennis enthusiasts.',
    icon: 'Trophy',
    thumbnail: 'file:///C:/Users/HUSSNAIN.COM/.gemini/antigravity/brain/fec02dc3-a62c-4d20-bd18-6ada510563ca/tennis_court_premium_1776635236529.png',
    price: 'Free',
    location: 'East Wing Sports Complex',
    timings: { open: '06:00 AM', close: '08:00 PM' },
    rules: ['Court shoes only', '60-minute limit during peak hours'],
  },
  {
    name: 'Swimming Pool',
    description: 'Temperature-controlled swimming pool with dedicated kids area.',
    icon: 'Waves',
    thumbnail: 'file:///C:/Users/HUSSNAIN.COM/.gemini/antigravity/brain/fec02dc3-a62c-4d20-bd18-6ada510563ca/swimming_pool_premium_1776635276374.png',
    price: 'Free',
    location: 'Main Pavilion, Level 2',
    timings: { open: '06:00 AM', close: '09:00 PM' },
    rules: ['Proper swimwear required', 'Shower before entry'],
  },
  {
    name: 'Club House (Gym)',
    description: 'State-of-the-art fitness center with premium equipment.',
    icon: 'Dumbbell',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&q=80',
    price: 'Free',
    location: 'Main Pavilion, Level 1',
    timings: { open: '05:00 AM', close: '10:00 PM' },
    rules: ['Guests not allowed', 'Sports shoes mandatory'],
  },
  {
    name: 'Guest Room',
    description: 'Comfortable ensuite rooms for society guests.',
    icon: 'Bed',
    thumbnail: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=400&q=80',
    price: 'Rs. 2500.00 / Night',
    location: 'Block B, Level 1',
    timings: { open: 'Check-in: 12 PM', close: 'Check-out: 10 AM' },
    rules: ['Maximum 2 adults per room', 'ID proof mandatory', 'No smoking'],
  },
  {
    name: 'Prayer Hall',
    description: 'A serene and quiet space for meditation and prayers.',
    icon: 'Heart',
    thumbnail: 'file:///C:/Users/HUSSNAIN.COM/.gemini/antigravity/brain/fec02dc3-a62c-4d20-bd18-6ada510563ca/prayer_hall_premium_1776635256452.png',
    price: 'Free',
    location: 'Block C, Ground Floor',
    timings: { open: '05:00 AM', close: '10:00 PM' },
    rules: ['Maintain silence', 'Keep shoes outside'],
  }
];
