export const AMENITIES_METADATA = [
  {
    name: 'Community Hall',
    description: 'A spacious venue for parties, workshops, and community gatherings.',
    icon: 'Users',
    thumbnail: require('../../../assets/amenities/amenity1.jpg'),
    price: 'Rs. 5000.00',
    location: 'Block A, Ground Floor',
    timings: { open: '09:00 AM', close: '11:00 PM' },
    rules: ['Advance booking required (48 hrs)', 'No loud music after 10 PM', 'Cleaning fee applies'],
  },
  {
    name: 'Tennis Court',
    description: 'Professional-grade clay courts for tennis enthusiasts.',
    icon: 'Trophy',
    thumbnail: require('../../../assets/amenities/amenity2.jpg'),
    price: 'Free',
    location: 'East Wing Sports Complex',
    timings: { open: '06:00 AM', close: '08:00 PM' },
    rules: ['Court shoes only', '60-minute limit during peak hours'],
  },
  {
    name: 'Swimming Pool',
    description: 'Temperature-controlled swimming pool with dedicated kids area.',
    icon: 'Waves',
    thumbnail: require('../../../assets/amenities/amenity3.jpg'),
    price: 'Free',
    location: 'Main Pavilion, Level 2',
    timings: { open: '06:00 AM', close: '09:00 PM' },
    rules: ['Proper swimwear required', 'Shower before entry'],
  },
  {
    name: 'Club House (Gym)',
    description: 'State-of-the-art fitness center with premium equipment.',
    icon: 'Dumbbell',
    thumbnail: require('../../../assets/amenities/amenity4.jpg'),
    price: 'Free',
    location: 'Main Pavilion, Level 1',
    timings: { open: '05:00 AM', close: '10:00 PM' },
    rules: ['Guests not allowed', 'Sports shoes mandatory'],
  },
  {
    name: 'Guest Room',
    description: 'Comfortable ensuite rooms for society guests.',
    icon: 'Bed',
    thumbnail: require('../../../assets/amenities/amenity5.jpg'),
    price: 'Rs. 2500.00 / Night',
    location: 'Block B, Level 1',
    timings: { open: 'Check-in: 12 PM', close: 'Check-out: 10 AM' },
    rules: ['Maximum 2 adults per room', 'ID proof mandatory', 'No smoking'],
  },
  {
    name: 'Prayer Hall',
    description: 'A serene and quiet space for meditation and prayers.',
    icon: 'Heart',
    thumbnail: require('../../../assets/amenities/amenity6.jpg'),
    price: 'Free',
    location: 'Block C, Ground Floor',
    timings: { open: '05:00 AM', close: '10:00 PM' },
    rules: ['Maintain silence', 'Keep shoes outside'],
  }
];
